### ISSUE TITLE
Releasing a held key should prevent the secondary key from typing

### ISSUE THREAD

**Issue by johnlindquist** [jamesnvc/Kaleidoscope-ToIfAlone#1]
Scenario:

Hold Motion Layer, Press "J" to move down.
Release Motion Layer while "J" is still down.

Actual:
"J" is typed.

Expected:
"J" is _not_ typed.

**Comment by algernon** [comment]
I think that calling `KeyboardHardware.maskHeldKeys()` on motion layer release would fix this case. It masks all currently held keys until they are released, which sounds like exactly what you'd want here.

**Comment by jamesnvc** [comment]
Thanks a lot for the bug report John!

**Comment by jamesnvc** [comment]
and thanks for the solution algernon 😁

**Comment by johnlindquist** [comment]
Beautiful, fix confirmed working! 👍
