### ISSUE TITLE
Possible to allow Shift or other modifiers with Tap key?

### ISSUE THREAD

**Issue by johnlindquist** [jamesnvc/Kaleidoscope-ToIfAlone#2]
I'd like to be able to have a 

{Key_Tab, SYMBOLS}

mapping, but then it becomes impossible to type "shift+tab" anywhere on the keyboard. Could you allow modifiers for the tap key?

**Comment by jamesnvc** [comment]
Hm...maybe I could add the ability to list blacklisted keys that don't get sent to the other layer? So you could write `{Key_Tab, SYMBOLS, {Key_LeftShift, Key_RightShift]}` or something like that.
My concern with just allowing modifiers is it's entirely possible someone has their modifier keys set to do something on the shifted layer.

**Comment by johnlindquist** [comment]
I think the logic is the other way around:

If a modifier key is held down before the key is pressed, do not trigger the Layer.

That way, if I'm holding shift, then press my Tab/SYMBOLS key, it knows I want Tab...

**Comment by jamesnvc** [comment]
Ah, that’s much easier! I will try to push a fix in a bit.

**Comment by jamesnvc** [comment]
Okay, trying not treating the key specially at all if a modifier is already held.

**Comment by johnlindquist** [comment]
This solves it, but breaks my other use case.

My SYMBOLS layer has Macros that use Shift. Now those Macros freak out and execute the Macro and the key "under" the layer extremely rapidly.

Also, my MOTION layer has Shift in the homerow on my left hand (which I use in combination with the "vim" keys on my right). Now it types the key in the main layer "under" the MOTION layer instead of Shift.

**Comment by jamesnvc** [comment]
hm, okay, I think I can address this...I will push in a moment

**Comment by jamesnvc** [comment]
Pushed, give it a try now?

**Comment by johnlindquist** [comment]
Sweet, everything appears to be working as expected! Thanks so much! 🎉
